version: "3.6" 

services:
  redis:
    restart: always
    image: redis:alpine
    container_name: gitlab_redis
    networks:
      - gitlab
    labels:
      - "traefik.enable=false"

  postgresql:
    restart: always
    image: postgres:alpine
    container_name: gitlab_postgresql
    environment:
      - POSTGRES_USER=${postgresql_db_username}
      - POSTGRES_PASSWORD=${postgresql_db_password}
      - POSTGRES_DB=${postgresql_db_database}
    volumes:
      - '.data/postgresql:/var/lib/postgresql/data'
    networks:
      - gitlab
    labels:
      - "traefik.enable=false"
  
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab_server
    restart: always
    environment:
      TZ: America/Bogota
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${SCHEME}://${DOMAIN_NAME}'
        # Database
        postgresql['enable'] = ${postgresql_enable}
        gitlab_rails['db_username'] = ${postgresql_db_username}
        gitlab_rails['db_password'] = ${postgresql_db_password}
        gitlab_rails['db_host'] = 'postgresql'
        gitlab_rails['db_port'] = '5432'
        gitlab_rails['db_database'] = ${postgresql_db_database}
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        # Redis
        redis['enable'] = ${redis_enable}
        gitlab_rails['redis_host'] = 'redis'
        gitlab_rails['redis_port'] = '6379'
        # Mail
        gitlab_rails['smtp_enable'] = ${smtp_enable}
        gitlab_rails['smtp_address'] = ${smtp_address}
        gitlab_rails['smtp_user_name'] = ${smtp_user_name}
        gitlab_rails['smtp_password'] = ${smtp_password}
        gitlab_rails['smtp_port'] = ${smtp_port}
        gitlab_rails['smtp_domain'] = ${smtp_domain}
        gitlab_rails['smtp_authentication'] = ${smtp_authentication}
        gitlab_rails['smtp_enable_starttls_auto'] = ${smtp_enable_starttls_auto}
        gitlab_rails['smtp_tls'] = ${smtp_tls}
        gitlab_rails['smtp_openssl_verify_mode'] = ${smtp_openssl_verify_mode}   
        # SSH
        gitlab_rails['gitlab_shell_ssh_port'] = '${SSH_PORT}'
        # Nginx
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        nginx['proxy_set_headers'] = {
                  "X-Forwarded-Proto" => "${SCHEME}",
                  "X-Forwarded-Ssl" => "${SSL}"
        }
        gitlab_rails['backup_keep_time'] = 86400
        gitlab_rails['backup_upload_connection'] = {
          'provider' => 'AWS',
          'region' => 'us-west-1',
          'aws_access_key_id' => ${ACCESS_KEY_ID},
          'aws_secret_access_key' => ${SECRET_ACCESS_KEY}
        }
    volumes:
      - '.data/gitlab/config:/etc/gitlab'
      - '.data/gitlab/logs:/var/log/gitlab'
      - '.data/gitlab/data:/var/opt/gitlab'    
    networks:
      - gitlab
      - app
    ports:
      - "${SSH_PORT}:22"
    depends_on:
      - postgresql
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.gitlab_backend=gitlab"
      - "traefik.frontend.rule=Host:${DOMAIN_NAME}"
      - "traefik.docker.network=app"

  gitlab-runner:
      image: gitlab/gitlab-runner:alpine
      container_name: gitlab_runner
      restart: always
      environment:
        - CI_SERVER_URL=${SCHEME}://${DOMAIN_NAME}/      
      networks:
        - gitlab
        - app      
      volumes:
        - './config/:/etc/gitlab-runner'
        - /var/run/docker.sock:/var/run/docker.sock:rw 

networks:
    app:
        external:
            name: app
    gitlab: ~        

docker-compose run --rm gitlab-runner register -n \
  --url http://172.25.0.5:80/ \
  --registration-token k6taHDqYfdfN4cMs-jC5 \
  --executor shell \
  --description "Shell runner devops-app" \
  --docker-image "docker:latest" \
  --docker-volumes /var/run/docker.sock:/var/run/docker.sock