version: "3.6" 

services:
  redis:
    restart: always
    image: redis:alpine
    container_name: gitlab_redis
    networks:
      - gitlab
    labels:
      - "traefik.enable=false"

  postgresql:
    restart: always
    image: postgres:alpine
    container_name: gitlab_postgresql
    environment:
      - POSTGRES_USER=gitlab
      - POSTGRES_PASSWORD=gitlab
      - POSTGRES_DB=gitdb
    volumes:
      - '/srv/gitlab/config:/var/lib/postgresql/data'
      # - postgresql:/var/lib/postgresql/data:Z
    networks:
      - gitlab
    labels:
      - "traefik.enable=false"
  
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab_server
    restart: always
    hostname: ${DOMAIN_NAME}    
    environment:
      TZ: Europe/Madrid
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://${DOMAIN_NAME}'
        # Database
        postgresql['enable'] = false
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = 'gitlab'
        gitlab_rails['db_host'] = 'postgresql'
        gitlab_rails['db_port'] = '5432'
        gitlab_rails['db_database'] = 'gitdb'
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        # Redis
        redis['enable'] = false
        gitlab_rails['redis_host'] = 'redis'
        gitlab_rails['redis_port'] = '6379'
        # Mail
        gitlab_rails['smtp_enable'] = ${smtp_enable}
        gitlab_rails['smtp_address'] = ${smtp_address}
        gitlab_rails['smtp_port'] = ${smtp_port}
        gitlab_rails['smtp_user_name'] = ${smtp_user_name}
        gitlab_rails['smtp_password'] = ${smtp_password}
        gitlab_rails['smtp_domain'] = ${smtp_domain}
        gitlab_rails['smtp_enable_starttls_auto'] = ${smtp_enable_starttls_auto}
        gitlab_rails['smtp_tls'] = ${smtp_tls}
        gitlab_rails['smtp_openssl_verify_mode'] = ${smtp_openssl_verify_mode}
        gitlab_rails['smtp_ssl'] = ${smtp_ssl}
        gitlab_rails['smtp_force_ssl'] = ${smtp_force_ssl}      
        # SSH
        gitlab_rails['gitlab_shell_ssh_port'] = '${SSH_PORT}'
        # Nginx
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        nginx['proxy_set_headers'] = {
                  "X-Forwarded-Proto" => "${SCHEME}",
                  "X-Forwarded-Ssl" => "${SSL}"
        }
        gitlab_rails['backup_keep_time'] = 86400
        gitlab_rails['backup_upload_connection'] = {
          'provider' => 'AWS',
          'region' => 'us-west-1',
          'aws_access_key_id' => ${ACCESS_KEY_ID},
          'aws_secret_access_key' => ${SECRET_ACCESS_KEY}
        }
    # volumes:
    #   - config:/etc/gitlab:Z
    #   - data:/var/opt/gitlab:Z
    #   - logs:/var/log/gitlab:Z
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'    
    networks:
      - gitlab
      - app
    ports:
      - "${SSH_PORT}:22"
    depends_on:
      - postgresql
      - redis
    labels:
      - "traefik.gitlab_backend=gitlab"
      - "traefik.frontend.rule=Host:gitlab.localhost"
      - "traefik.frontend.rule=Host:${DOMAIN_NAME}"
      - "traefik.docker.network=traefik"
      - "traefik.port=80"

networks:
    app:
        external:
            name: app
    gitlab: ~        

# volumes:
#   config:
#   data:
#   logs:
#   postgresql:
